import React from 'react';
import { 
  Inbox, 
  CheckCircle2, 
  AlertTriangle, 
  ShieldAlert, 
  Percent,
  Clock,
  ArrowRight
} from 'lucide-react';
import { MOCK_CFO_BRIEF, MOCK_INVOICES } from '../services/mockData';
import { Link } from 'react-router-dom';

export const Dashboard: React.FC = () => {
  // Calculations based on mock data
  const totalPending = MOCK_INVOICES.filter(i => i.status === 'Pending').length;
  const totalApproved = MOCK_INVOICES.filter(i => i.status === 'Approved').length;
  const totalReview = MOCK_INVOICES.filter(i => i.status === 'Review').length;
  const totalAlerts = MOCK_INVOICES.filter(i => i.status === 'Investigate' || i.recommendation === 'INVESTIGATE').length;
  
  const avgRiskScore = Math.round(
    MOCK_INVOICES.reduce((acc, curr) => acc + curr.riskScore, 0) / MOCK_INVOICES.length
  );

  const stats = [
    { name: 'Pending Approval', value: totalPending, icon: Inbox, color: 'text-amber-600', bg: 'bg-amber-50 border-amber-200' },
    { name: 'Approved Invoices', value: totalApproved, icon: CheckCircle2, color: 'text-emerald-600', bg: 'bg-emerald-50 border-emerald-200' },
    { name: 'Needs Review', value: totalReview, icon: AlertTriangle, color: 'text-orange-600', bg: 'bg-orange-50 border-orange-200' },
    { name: 'Fraud Alerts', value: totalAlerts, icon: ShieldAlert, color: 'text-rose-600', bg: 'bg-rose-50 border-rose-200' },
    { name: 'Average Risk Score', value: `${avgRiskScore}/100`, icon: Percent, color: 'text-slate-600', bg: 'bg-slate-50 border-slate-200' },
  ];

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Overview Cards */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-6">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <div 
              key={stat.name} 
              className={`p-6 rounded-xl border bg-white shadow-sm flex flex-col justify-between h-32 transition-all hover:shadow-md`}
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">{stat.name}</span>
                <div className={`p-2 rounded-lg ${stat.bg}`}>
                  <Icon className={`h-5 w-5 ${stat.color}`} />
                </div>
              </div>
              <span className="text-2xl font-bold text-slate-800">{stat.value}</span>
            </div>
          );
        })}
      </div>

      {/* CFO Morning Brief & Recent Activity */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* CFO Morning Brief */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden flex flex-col justify-between">
          <div className="p-6 border-b border-slate-200">
            <h2 className="text-lg font-bold text-slate-800 tracking-wide flex items-center space-x-2">
              <span>CFO Morning Brief</span>
              <span className="px-2 py-0.5 text-[10px] font-bold bg-emerald-100 text-emerald-800 rounded-full uppercase">
                AI Generated
              </span>
            </h2>
          </div>
          <div className="p-8 flex-1 bg-slate-950 text-slate-300 font-serif leading-relaxed text-lg border-b border-slate-900">
            "{MOCK_CFO_BRIEF}"
          </div>
          <div className="p-4 bg-slate-50 flex items-center justify-between px-6 text-xs text-slate-500 font-medium">
            <span>Generated by Final Decision Agent</span>
            <span>Target: Today's AP Liquidity</span>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm flex flex-col justify-between">
          <div className="p-6 border-b border-slate-200">
            <h2 className="text-lg font-bold text-slate-800 tracking-wide">Recent Activity</h2>
          </div>
          <div className="p-6 flex-1 space-y-4">
            {MOCK_INVOICES.slice(0, 3).map((invoice) => (
              <div key={invoice.id} className="flex items-start space-x-3 p-2 hover:bg-slate-50 rounded-lg transition-colors">
                <div className="p-2 bg-slate-100 rounded-lg text-slate-600 mt-1">
                  <Clock className="h-4 w-4" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold text-slate-800">{invoice.vendorName}</p>
                  <p className="text-xs text-slate-500">Invoice {invoice.id} — {invoice.currency}{invoice.amount.toLocaleString()}</p>
                  <span className={`inline-block mt-1 text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                    invoice.status === 'Approved' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' :
                    invoice.status === 'Pending' ? 'bg-amber-50 text-amber-700 border border-amber-100' :
                    'bg-slate-50 text-slate-600 border border-slate-100'
                  }`}>
                    {invoice.status}
                  </span>
                </div>
                <Link to={`/invoices/${invoice.id}`} className="text-slate-400 hover:text-emerald-600 transition-colors">
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
